#!/bin/bash

# detect if the venv is active
INVENV = $(python3 -c 'import sys; print("1" if hasattr(sys, "real_prefix") else "0")')

# setup python3 environment if not active
if [ ! $INVENV ]
then
    # create and activate venv
    python3 -m venv env
    source env/bin/activate
    # install antlr4-python3-runtime
    pip3 install antlr4-python3-runtime
    # generate parser/scanner/listener files
    java org.antlr.v4.Tool -Dlanguage=Python3 Little.g4
fi

# run our python script and pass arg1 as input
python3 Main.py $1