#!/bin/bash

# generate lexer file if it doesn't exist
if [ ! -f "Little.py" ]; then
    java org.antlr.v4.Tool -Dlanguage=Python3 Little.g4
fi

# run our python script and pass arg1 as input
python3 Main.py $1